### Project specific config ###
language: generic

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

dist: trusty

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false


addons:
  artifacts:
    paths:
      - out/atom-amd64.deb
      - out/atom.x86_64.rpm
      - out/atom-amd64.tar.gz
    target_paths: travis-artifacts/$TRAVIS_BUILD_ID
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - fakeroot
    - git
    - libsecret-1-dev
    - rpm
    - libx11-dev
    - libxkbfile-dev
